# Generated by Django 6.0.3 on 2026-03-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("colour_hex", models.CharField(blank=True, default="", max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=40, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial (some errors)"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("count_created", models.PositiveIntegerField(default=0)),
                ("count_skipped", models.PositiveIntegerField(default=0)),
                ("count_errors", models.PositiveIntegerField(default=0)),
                ("error_detail", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_logs",
                        to="accounts.account",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "import log",
                "verbose_name_plural": "import logs",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "default_nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("income", "Income"),
                            ("fixed_mandatory", "Fixed mandatory"),
                            ("fixed_discretionary", "Fixed discretionary"),
                            ("variable_mandatory", "Variable mandatory"),
                            ("variable_discretionary", "Variable discretionary"),
                            ("savings", "Savings"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="transactions.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "sub-category",
                "verbose_name_plural": "sub-categories",
                "ordering": ["category__order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="CategorizationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200)),
                (
                    "target_field",
                    models.CharField(
                        choices=[
                            ("description_raw", "Raw description"),
                            ("merchant_name", "Merchant name"),
                        ],
                        default="merchant_name",
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="transactions.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="transactions.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "categorization rule",
                "verbose_name_plural": "categorization rules",
                "ordering": ["-priority", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("income", "Income"),
                            ("fixed_mandatory", "Fixed mandatory"),
                            ("fixed_discretionary", "Fixed discretionary"),
                            ("variable_mandatory", "Variable mandatory"),
                            ("variable_discretionary", "Variable discretionary"),
                            ("savings", "Savings"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "categorization_source",
                    models.CharField(
                        choices=[
                            ("default", "Default (Unknown)"),
                            ("rule", "Rule applied"),
                            ("ai", "AI categorized"),
                            ("manual", "Manual"),
                        ],
                        default="default",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount_chf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("description_raw", models.CharField(max_length=500)),
                (
                    "merchant_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("is_reconciled", models.BooleanField(default=False)),
                ("is_ignored", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_internal_transfer", models.BooleanField(default=False)),
                ("import_hash", models.CharField(max_length=40, unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="accounts.card",
                    ),
                ),
                (
                    "categorization_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.categorizationrule",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "paired_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paired_by",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BudgetTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_targets",
                        to="transactions.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget target",
                "verbose_name_plural": "budget targets",
                "ordering": ["-period", "category__order"],
                "unique_together": {("category", "period")},
            },
        ),
    ]
