# Generated by Django 6.0.3 on 2026-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
