# Generated by Django 6.0.3 on 2026-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
