# Generated by Django 6.0.3 on 2026-04-23 07:40

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_budget_targets(apps, schema_editor):
    """
    Avant de rendre category_id unique, on supprime les doublons.
    On garde la ligne avec le period le plus récent pour chaque catégorie.
    """
    BudgetTarget = apps.get_model("transactions", "BudgetTarget")
    seen = set()
    # Ordonner par period desc pour garder le plus récent en premier
    for target in BudgetTarget.objects.order_by("-period"):
        if target.category_id in seen:
            target.delete()
        else:
            seen.add(target.category_id)


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_subcategory_is_system"),
    ]

    operations = [
        migrations.RunPython(deduplicate_budget_targets, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="budgettarget",
            options={
                "ordering": ["category__order"],
                "verbose_name": "budget target",
                "verbose_name_plural": "budget targets",
            },
        ),
        migrations.AlterUniqueTogether(
            name="budgettarget",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="budgettarget",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_target",
                to="transactions.category",
            ),
        ),
        migrations.RemoveField(
            model_name="budgettarget",
            name="period",
        ),
    ]
