# Generated by Django 6.0.3 on 2026-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_budgettarget_remove_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="import_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
