# Generated by Django 6.0.3 on 2026-04-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_import_hash_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="import_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="transactions.importlog",
            ),
        ),
    ]
