# Generated by Django 6.0.3 on 2026-04-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_transaction_add_import_log_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="file_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
