# Generated by Django 6.0.3 on 2026-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_importlog_file_hash_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="importlog",
            name="is_encrypted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importlog",
            name="stored_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="importlog",
            name="stored_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
