# Generated by Django 6.0.3 on 2026-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0010_rehash_ubs_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="importlog",
            name="date_max",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importlog",
            name="date_min",
            field=models.DateField(blank=True, null=True),
        ),
    ]
