# Generated by Django 6.0.3 on 2026-05-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_import_log_date_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="import_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="transactions.importlog",
            ),
        ),
    ]
