# Generated by Django 6.0.3 on 2026-05-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_transaction_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorizationrule",
            name="target_field",
            field=models.CharField(
                choices=[
                    ("description_raw", "Raw description"),
                    ("merchant_name", "Merchant name (legacy)"),
                    ("display_name", "Display name (clean)"),
                ],
                default="display_name",
                max_length=20,
            ),
        ),
    ]
