# Generated by Django 6.0.5 on 2026-06-02 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_account_members_data"),
        ("transactions", "0014_categorization_rule_display_name_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="file_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="importlog",
            constraint=models.UniqueConstraint(
                fields=("file_hash", "account"), name="importlog_file_hash_account_uniq"
            ),
        ),
    ]
