# Generated by Django 6.0.6 on 2026-06-22 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0020_backfill_categorizationrule_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subcategory",
            name="subcategory_category_name_uniq",
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("category", "name"),
                name="subcategory_system_category_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("category", "name", "owner"),
                name="subcategory_owner_category_name_uniq",
            ),
        ),
    ]
