# Generated by Django 6.0.6 on 2026-06-24 02:19
#
# #213 — Couche-2 ORM fail-closed (OwnedManager). Migration d'ÉTAT uniquement :
# aucune modification de schéma DB. Elle enregistre base_manager_name="_base" et le
# changement de managers (use_in_migrations=False → managers neutres au runtime des
# migrations). Requise pour que `makemigrations --check` reste vert en CI.

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0022_budgettarget_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgettarget",
            options={
                "base_manager_name": "_base",
                "ordering": ["category__order"],
                "verbose_name": "budget target",
                "verbose_name_plural": "budget targets",
            },
        ),
        migrations.AlterModelOptions(
            name="categorizationrule",
            options={
                "base_manager_name": "_base",
                "ordering": ["-priority", "keyword"],
                "verbose_name": "categorization rule",
                "verbose_name_plural": "categorization rules",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "_base",
                "ordering": ["order", "name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "base_manager_name": "_base",
                "ordering": ["category__order", "name"],
                "verbose_name": "sub-category",
                "verbose_name_plural": "sub-categories",
            },
        ),
        migrations.AlterModelManagers(
            name="budgettarget",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_base", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="categorizationrule",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_base", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_base", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subcategory",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_base", django.db.models.manager.Manager()),
            ],
        ),
    ]
