# Generated by Django 6.0.6 on 2026-06-26 07:59
# Étendue manuellement (#203) : backfill des lignes déjà fuitées par l'ancien
# SET_NULL, en plus du passage à CASCADE. (Finding CodeRabbit sur la PR.)
# Le verrou CheckConstraint owner/is_system est volontairement DIFFÉRÉ : il casse
# les nombreux tests/chemins qui créent une catégorie « système » en raccourci
# (owner=None sans is_system=True) → refactor séparé « is_system explicite partout ».

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remediate_leaked_owner_rows(apps, schema_editor):
    """Nettoie les lignes déjà fuitées par l'ancien on_delete=SET_NULL.

    Invariant (toujours vrai dans tous les chemins de création) :
        catégorie SYSTÈME  → is_system=True  ET owner IS NULL
        catégorie PERSO    → is_system=False ET owner IS NOT NULL

    Avant #203, supprimer un user mettait owner=NULL sur ses lignes perso →
    état (is_system=False, owner NULL) = perso orpheline traitée comme système.
    L'user est parti (c'est pourquoi owner est NULL) → impossible de réattribuer :
    on SUPPRIME ces lignes (les transactions liées survivent, category=SET_NULL).

    Sur une DB normale (système seedé is_system=True, perso créées owner=user),
    ces lignes n'existent QUE si un user a été supprimé sous l'ancien SET_NULL →
    purge ciblée, sans risque pour les vraies catégories système.
    """
    Category = apps.get_model("transactions", "Category")
    SubCategory = apps.get_model("transactions", "SubCategory")
    for model in (Category, SubCategory):
        # Perso orpheline (leak réel) → suppression (CASCADE enfants, tx SET_NULL).
        model.objects.filter(is_system=False, owner__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0023_alter_budgettarget_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Remédier l'existant AVANT de durcir le schéma.
        migrations.RunPython(
            remediate_leaked_owner_rows,
            migrations.RunPython.noop,  # purge de données invalides → pas de reverse
        ),
        # 2. on_delete=SET_NULL → CASCADE (empêche la fuite sur les futurs delete).
        migrations.AlterField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
