# Generated by Django 6.0.3 on 2026-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_profile_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_currency",
            field=models.CharField(
                default="CHF",
                help_text="ISO 4217 currency code: CHF, EUR, GBP...",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                default="fr",
                help_text="BCP 47 language tag: fr, en, de...",
                max_length=10,
            ),
        ),
    ]
