# Generated by Django 6.0.3 on 2026-03-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("current", "Checking account"),
                            ("savings", "Savings account"),
                            ("pension_3a", "3rd pillar (3a)"),
                            ("pension_lp", "Vested benefits (LP)"),
                            ("investment", "Investment account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "ordering": ["bank__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=2)),
                ("default_currency", models.CharField(max_length=3)),
                ("icon_slug", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "bank",
                "verbose_name_plural": "banks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CheckingAccount",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="checking_account",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                ("bic", models.CharField(blank=True, default="", max_length=11)),
            ],
            options={
                "verbose_name": "checking account",
                "verbose_name_plural": "checking accounts",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="accounts.bank",
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                "verbose_name": "exchange rate",
                "verbose_name_plural": "exchange rates",
                "ordering": ["-date"],
                "unique_together": {("date", "from_currency", "to_currency")},
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_four", models.CharField(max_length=4)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        default="debit",
                        max_length=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checking_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="accounts.checkingaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "card",
                "verbose_name_plural": "cards",
                "ordering": ["checking_account", "last_four"],
            },
        ),
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "balance_chf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("import", "File import"), ("manual", "Manual entry")],
                        default="import",
                        max_length=10,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "balance snapshot",
                "verbose_name_plural": "balance snapshots",
                "ordering": ["-date"],
                "unique_together": {("account", "date")},
            },
        ),
    ]
