# Generated by Django 6.0.3 on 2026-04-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_account_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="savings_account",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5
                    ),
                ),
                (
                    "account_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "verbose_name": "savings account",
                "verbose_name_plural": "savings accounts",
            },
        ),
    ]
