# Generated by Django 6.0.3 on 2026-04-03 10:44

from django.db import migrations, models


def current_to_checking(apps, schema_editor):
    # Rename the stored value "current" → "checking" for all existing rows.
    # AlterField above only updates the choices list (Python-side validation),
    # not the actual string values already stored in the DB.
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(account_type="current").update(account_type="checking")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_savingsaccount"),
    ]

    operations = [
        migrations.RunPython(current_to_checking, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking account"),
                    ("savings", "Savings account"),
                    ("pension_3a", "3rd pillar (3a)"),
                    ("pension_lp", "Vested benefits (LP)"),
                    ("investment", "Investment account"),
                ],
                max_length=20,
            ),
        ),
    ]
