# Generated by Django 6.0.3 on 2026-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="contract_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
