# Generated by Django 6.0.3 on 2026-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_account_contract_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="domain",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
