# Generated by Django 6.0.3 on 2026-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_bank_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesnapshot",
            name="computed_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesnapshot",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
