# Generated by Django 6.0.3 on 2026-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_balancesnapshot_computed_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CHF", "CHF — Franc suisse"),
                    ("EUR", "EUR — Euro"),
                    ("GBP", "GBP — Livre sterling"),
                    ("USD", "USD — Dollar américain"),
                ],
                default="CHF",
                max_length=3,
            ),
        ),
    ]
