# Generated by Django 6.0.3 on 2026-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_account_currency_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkingaccount",
            name="iban",
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
