# Generated by Django 6.0.3 on 2026-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_checkingaccount_iban_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkingaccount",
            name="iban",
            field=models.CharField(
                blank=True, default=None, max_length=34, null=True, unique=True
            ),
        ),
    ]
