# Generated by Django 6.0.3 on 2026-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_account_iban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking account"),
                    ("savings", "Savings account"),
                    ("pension_3a", "3rd pillar (3a)"),
                    ("pension_lp", "Vested benefits (LP)"),
                    ("investment", "Investment account / Titres"),
                    ("card", "Credit / Debit card"),
                    ("insurance", "Life insurance / Assurance vie"),
                    ("brokerage", "Brokerage / Compte titres"),
                ],
                max_length=20,
            ),
        ),
    ]
