# Generated by Django 6.0.3 on 2026-05-14 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_account_account_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membres ayant accès",
            ),
        ),
    ]
