# Generated by Django 6.0.5 on 2026-06-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_rename_bank_institution"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeInsuranceDetails",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="life_insurance_details",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "fonds_euro_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "fonds_euro_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "management_fee_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "life insurance details",
                "verbose_name_plural": "life insurance details",
            },
        ),
        migrations.CreateModel(
            name="PensionDetails",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pension_details",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "annual_limit_chf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "contributions_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "management_fee_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "pension details",
                "verbose_name_plural": "pension details",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="closed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="fiscal_country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="account",
            name="opened_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking account"),
                    ("savings", "Savings account"),
                    ("pension_3a", "3rd pillar (3a)"),
                    ("pension_lp", "Vested benefits (LP)"),
                    ("investment", "Investment account / Titres"),
                    ("card", "Credit / Debit card"),
                    ("insurance", "Life insurance / Assurance vie"),
                    ("brokerage", "Brokerage / Compte titres"),
                    ("crypto", "Crypto exchange"),
                ],
                max_length=20,
            ),
        ),
    ]
