# Generated by Django 6.0.6 on 2026-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_account_3a_fields_and_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="category",
            field=models.CharField(
                choices=[
                    ("bank", "Banque"),
                    ("investment", "Investissement"),
                    ("crypto", "Crypto"),
                ],
                default="bank",
                max_length=20,
            ),
        ),
    ]
