# Generated by Django 6.0.6 on 2026-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_checkingaccount_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="colour_hex",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="institution",
            name="colour_hex",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
    ]
