# Generated by Django 6.0.6 on 2026-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_backfill_colour_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
